### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [getlantern/wal#3]
Hello, under what license is this project released under ? Thank-you.

**Comment by inosvaruag** [comment]
+1. Can you please add a LICENSE file for the project?

Without it, other peers cannot extend, modify, and improve this.

**Comment by inosvaruag** [comment]
@hwh33 tagging the most recent contributor

**Comment by hwh33** [comment]
[Wish granted!](https://github.com/getlantern/wal/blob/master/LICENSE)

**Comment by inosvaruag** [comment]
Thank you!
